<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="appsettings.json"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.7"/>
        <PackageReference Include="LibVLCSharp" Version="3.9.6"/>
        <PackageReference Include="LibVLCSharp.WinForms" Version="3.9.6"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5"/>
        <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj"/>
        <ProjectReference Include="..\Contracts\Contracts.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Update="Forms\Dialogs\CreateGroupChatDialog.cs">
            <SubType>Form</SubType>
        </Compile>
        <Compile Update="Forms\Dialogs\FriendsDialog.cs">
            <SubType>Form</SubType>
        </Compile>
        <Compile Update="Forms\Dialogs\InputDialog.cs">
            <SubType>Form</SubType>
        </Compile>
        <Compile Update="Forms\Dialogs\ProfileSettingsDialog.cs">
            <SubType>Form</SubType>
        </Compile>
        <Compile Update="UI\Factory\ChatPanelUC.cs">
            <SubType>UserControl</SubType>
        </Compile>
        <Compile Update="UI\Factory\FriendRequestPanelUC.cs">
            <SubType>UserControl</SubType>
        </Compile>
        <Compile Update="UI\Factory\FriendSelectPanelUC.cs">
            <SubType>UserControl</SubType>
        </Compile>
        <Compile Update="UI\Factory\MessagePanelUC.cs">
            <SubType>UserControl</SubType>
        </Compile>
        <Compile Update="UI\Factory\ProfilePanelUC.cs">
            <SubType>UserControl</SubType>
        </Compile>
        <Compile Update="UI\UserControls\FriendPanelUC.cs">
            <SubType>UserControl</SubType>
        </Compile>
        <Compile Update="UI\UserControls\ContextMenuUC.cs">
            <SubType>UserControl</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>