//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account.
        /// </summary>
        internal static string AuthForm_HasAccount {
            get {
                return ResourceManager.GetString("AuthForm_HasAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string AuthForm_Login {
            get {
                return ResourceManager.GetString("AuthForm_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account.
        /// </summary>
        internal static string AuthForm_NoAccount {
            get {
                return ResourceManager.GetString("AuthForm_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string AuthForm_Register {
            get {
                return ResourceManager.GetString("AuthForm_Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string AuthForm_Password {
            get {
                return ResourceManager.GetString("AuthForm_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string AuthForm_Username {
            get {
                return ResourceManager.GetString("AuthForm_Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit chat.
        /// </summary>
        internal static string ClientForm_EditChat {
            get {
                return ResourceManager.GetString("ClientForm_EditChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit message.
        /// </summary>
        internal static string ClientForm_EditMessage {
            get {
                return ResourceManager.GetString("ClientForm_EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter message.
        /// </summary>
        internal static string ClientForm_EnterMessage {
            get {
                return ResourceManager.GetString("ClientForm_EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Chats.
        /// </summary>
        internal static string ClientForm_LoadingChats {
            get {
                return ResourceManager.GetString("ClientForm_LoadingChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available servers.
        /// </summary>
        internal static string ClientForm_NoAvailableServers {
            get {
                return ResourceManager.GetString("ClientForm_NoAvailableServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ClientForm_RefreshServers {
            get {
                return ResourceManager.GetString("ClientForm_RefreshServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ClientForm_Search {
            get {
                return ResourceManager.GetString("ClientForm_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextMenuUC_Delete {
            get {
                return ResourceManager.GetString("ContextMenuUC_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ContextMenuUC_Edit {
            get {
                return ResourceManager.GetString("ContextMenuUC_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DialogService_Error {
            get {
                return ResourceManager.GetString("DialogService_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string DialogService_Info {
            get {
                return ResourceManager.GetString("DialogService_Info", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string CreateGroupChatDialog_AddedToGroup {
            get {
                return ResourceManager.GetString("CreateGroupChatDialog_AddedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friends.
        /// </summary>
        internal static string CreateGroupChatDialog_AddFriends {
            get {
                return ResourceManager.GetString("CreateGroupChatDialog_AddFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string CreateGroupChatDialog_AddToGroup {
            get {
                return ResourceManager.GetString("CreateGroupChatDialog_AddToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateGroupChatDialog_CreateGroupChat {
            get {
                return ResourceManager.GetString("CreateGroupChatDialog_CreateGroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter group name.
        /// </summary>
        internal static string CreateGroupChatDialog_EnterGroupName {
            get {
                return ResourceManager.GetString("CreateGroupChatDialog_EnterGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string CreateGroupChatDialog_GroupName {
            get {
                return ResourceManager.GetString("CreateGroupChatDialog_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend requests.
        /// </summary>
        internal static string FriendListDialog_FriendRequests {
            get {
                return ResourceManager.GetString("FriendListDialog_FriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friend requests yet.
        /// </summary>
        internal static string FriendListDialog_NoFriendRequests {
            get {
                return ResourceManager.GetString("FriendListDialog_NoFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here yet.
        /// </summary>
        internal static string FriendListDialog_NoFriends {
            get {
                return ResourceManager.GetString("FriendListDialog_NoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string FriendListDialog_FriendList {
            get {
                return ResourceManager.GetString("FriendListDialog_FriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string FriendSelectPanelUC_Add {
            get {
                return ResourceManager.GetString("FriendSelectPanelUC_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image.
        /// </summary>
        internal static string ImageHelper_SelectImageTitle {
            get {
                return ResourceManager.GetString("ImageHelper_SelectImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string InputDialog_Save {
            get {
                return ResourceManager.GetString("InputDialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        internal static string ProfilePanelUC_AddFriend {
            get {
                return ResourceManager.GetString("ProfilePanelUC_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter friend name.
        /// </summary>
        internal static string ProfilePanelUC_EnterFriendName {
            get {
                return ResourceManager.GetString("ProfilePanelUC_EnterFriendName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ProfilePanelUC_Settings {
            get {
                return ResourceManager.GetString("ProfilePanelUC_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change username.
        /// </summary>
        internal static string ProfileSettingsDialog_ChangeName {
            get {
                return ResourceManager.GetString("ProfileSettingsDialog_ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ProfileSettingsDialog_ChangePassword {
            get {
                return ResourceManager.GetString("ProfileSettingsDialog_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ProfileSettingsDialog_Edit {
            get {
                return ResourceManager.GetString("ProfileSettingsDialog_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new username.
        /// </summary>
        internal static string ProfileSettingsDialog_EnterNewName {
            get {
                return ResourceManager.GetString("ProfileSettingsDialog_EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string ProfileSettingsDialog_EnterNewPassword {
            get {
                return ResourceManager.GetString("ProfileSettingsDialog_EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ProfileSettingsDialog_Password {
            get {
                return ResourceManager.GetString("ProfileSettingsDialog_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string ProfileSettingsDialog_Username {
            get {
                return ResourceManager.GetString("ProfileSettingsDialog_Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server is unavailable. Please try to start the application later..
        /// </summary>
        internal static string Program_ConnectionError {
            get {
                return ResourceManager.GetString("Program_ConnectionError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string Program_ConnectionErrorTitle {
            get {
                return ResourceManager.GetString("Program_ConnectionErrorTitle", resourceCulture);
            }
        }
    }
}
